server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/serratecflix
spring.datasource.username=postgres
spring.datasource.password=ga22042004

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##Envio de email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=serratecflix5@gmail.com
spring.mail.password=iwyr fmtr zspd rhwf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#spring.jpa.hibernate.ddl-auto=create-drop
